language: java
install: mvn install --quiet -DskipTests=true -B
script: mvn test --quiet -B
jdk:
  - openjdk6
  - oraclejdk7
# Test failure on JDK8 - https://tools.codice.org/jira/browse/DDF-478
#  - oraclejdk8
