language: java
install: mvn install --quiet -DskipTests=true -B
script: mvn test --quiet -B
jdk:
  - openjdk6
  - oraclejdk7
# Build failure on JDK8. DDF JIRA Bug: https://tools.codice.org/jira/browse/DDF-476
#  - oraclejdk8
