language: java
install: mvn install --quiet -DskipTests=true -B
script: mvn test --quiet -B
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
before_install:
  sudo pip install codecov
after_success:
  codecov
